if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif

set nocompatible	" Use Vim defaults (much better!)
set bs=indent,eol,start		" allow backspacing over everything in insert mode
"set ai			" always set autoindenting on
"set backup		" keep a backup file
set viminfo='20,\"50	" read/write a .viminfo file, don't store more
			" than 50 lines of registers
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time

" Only do this part when compiled with support for autocommands
if has("autocmd")
  augroup fedora
  autocmd!
  " In text files, always limit the width of text to 78 characters
  " autocmd BufRead *.txt set tw=78
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
  " don't write swapfile on most commonly used directories for NFS mounts or USB sticks
  autocmd BufNewFile,BufReadPre /media/*,/run/media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
  " start with spec file template
  autocmd BufNewFile *.spec 0r /usr/share/vim/vimfiles/template.spec
  augroup END
endif

if has("cscope") && filereadable("/usr/bin/cscope")
   set csprg=/usr/bin/cscope
   set csto=0
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
      cs add $PWD/cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
      cs add $CSCOPE_DB
   endif
   set csverb
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin on

if &term=="xterm"
     set t_Co=8
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"
syntax on
set background=dark
set number
"set nocompatible
"filetype indent plugin on
"set expandtab
"set smarttab
"set autoindent
"call pathogen#infect()


"colorscheme 0x7A69_dark
""colorscheme 256-gra
"colorscheme 256-jungle
""colorscheme 3dglasses
"colorscheme abra
""colorscheme adam
"colorscheme adaryn
""colorscheme adobe
"colorscheme adrian
""colorscheme advantage
"colorscheme af
""colorscheme aiseered
"colorscheme anotherdark
""colorscheme ansi_blows
"colorscheme apprentice
""colorscheme aqua
"colorscheme ashen
""colorscheme asmanian_blood
"colorscheme astronaut
""colorscheme asu1dark
"colorscheme atom
""colorscheme automation
"colorscheme autumnleaf
""colorscheme autumn
"colorscheme babymate256
""colorscheme badwolf
"colorscheme base16-atelierdune
""colorscheme basic
"colorscheme baycomb
""colorscheme bayQua
"colorscheme bclear
""colorscheme beachcomber
"colorscheme beauty256
""colorscheme bensday
"colorscheme billw
""colorscheme biogoo
"colorscheme black_angus
""colorscheme blackbeauty
"colorscheme blackboard
""colorscheme blackdust
"colorscheme blacklight
""colorscheme BlackSea
"colorscheme blazer
""colorscheme blink
"colorscheme bluechia
""colorscheme bluedrake
"colorscheme bluegreen
""colorscheme blueprint
"colorscheme blueshift
""colorscheme blue
"colorscheme bluez
""colorscheme blugrine
"colorscheme bmichaelsen
""colorscheme bocau
"colorscheme bog
""colorscheme borland
"colorscheme breeze
""colorscheme brookstream
"colorscheme brown
""colorscheme bubblegum
"colorscheme burnttoast256
""colorscheme busierbee
"colorscheme busybee
""colorscheme buttercream
"colorscheme bvemu
""colorscheme bw
"colorscheme C64
""colorscheme cake16
"colorscheme calmar256-light
""colorscheme camo
"colorscheme campfire
""colorscheme candycode
"colorscheme candyman
""colorscheme candy
"colorscheme caramel
""colorscheme carrot
"colorscheme carvedwoodcool
""colorscheme carvedwood
"colorscheme cascadia
""colorscheme chance-of-storm
"colorscheme charged-256
""colorscheme charon
"colorscheme Chasing_Logic
""colorscheme chela_light
"colorscheme chlordane
""colorscheme ChocolateLiquor
"colorscheme ChocolatePapaya
""colorscheme chocolate
"colorscheme chrysoprase
""colorscheme ciscoacl
"colorscheme clarity
""colorscheme cleanphp
"colorscheme cleanroom
""colorscheme clearance
"colorscheme cloudy
""colorscheme clue
"colorscheme cobaltish
""colorscheme cobalt
"colorscheme codeblocks_dark
""colorscheme codeburn
"colorscheme CodeFactoryv3
""colorscheme codeschool
"colorscheme coffee
""colorscheme coldgreen
"colorscheme colorer
""colorscheme colorful256
"colorscheme colorful
""colorscheme colorscheme_template
"colorscheme colorzone
""colorscheme contrasty
"colorscheme cool
""colorscheme corn
"colorscheme corporation
""colorscheme cthulhian
"colorscheme custom
""colorscheme c
"colorscheme d8g_01
""colorscheme d8g_02
"colorscheme d8g_03
""colorscheme d8g_04
"colorscheme dante
""colorscheme darkblack
"colorscheme darkblue2
""colorscheme darkBlue
"colorscheme darkbone
""colorscheme darkburn
"colorscheme darkdot
""colorscheme darkeclipse
"colorscheme darkerdesert
""colorscheme darker-robin
"colorscheme darkocean
""colorscheme darkrobot
"colorscheme darkroom
""colorscheme dark-ruby
"colorscheme darkslategray
""colorscheme darkspectrum
"colorscheme darktango
""colorscheme darkzen
"colorscheme darkZ
""colorscheme darth
"colorscheme dawn
""colorscheme delek
"colorscheme delphi
""colorscheme denim
"colorscheme derefined
""colorscheme desert256v2
"colorscheme desert256
""colorscheme desertedoceanburnt
"colorscheme desertedocean
""colorscheme desertEx
"colorscheme desert
""colorscheme detailed
"colorscheme devbox-dark-256
""colorscheme DevC++
"colorscheme deveiate
""colorscheme developer
"colorscheme disciple
""colorscheme distinguished
"colorscheme django
""colorscheme donbass
"colorscheme doorhinge
""colorscheme doriath
"colorscheme dual
""colorscheme dull
"colorscheme dusk
""colorscheme earendel
"colorscheme earthburn
""colorscheme earth
"colorscheme eclipse
""colorscheme eclm_wombat
"colorscheme ecostation
""colorscheme editplus
"colorscheme edo_sea
""colorscheme ego
"colorscheme ekin
""colorscheme ekvoli
"colorscheme elda
""colorscheme elise
"colorscheme elisex
""colorscheme elrodeo
"colorscheme emacs
""colorscheme enzyme
"colorscheme evening_2
""colorscheme far
"colorscheme felipec
""colorscheme fine_blue
"colorscheme flatcolor
""colorscheme flatlandia
"colorscheme flatland
""colorscheme flattr
"colorscheme flatui
""colorscheme fnaqevan
"colorscheme fog
""colorscheme fokus
"colorscheme forneus
""colorscheme freya
"colorscheme frood
""colorscheme fruidle
"colorscheme fruit
""colorscheme fruity
"colorscheme fu
""colorscheme gardener
"colorscheme gemcolors
""colorscheme gentooish
"colorscheme getafe
""colorscheme getfresh
"colorscheme github
""colorscheme gobo
"colorscheme golded
""colorscheme golden
"colorscheme google
""colorscheme gor
"colorscheme gotham256
""colorscheme gotham
"colorscheme gothic
""colorscheme grape
"colorscheme gravity
""colorscheme graywh
"colorscheme grb256
""colorscheme greens
"colorscheme greenvision
""colorscheme grey2
"colorscheme greyblue
""colorscheme grishin
"colorscheme gruvbox
""colorscheme guardian
"colorscheme guepardo
""colorscheme h80
"colorscheme habiLight
""colorscheme harlequin
"colorscheme heliotrope
""colorscheme hemisu
"colorscheme herald
""colorscheme herokudoc-
"colorscheme herokudoc
""colorscheme holokai
"colorscheme hornet
""colorscheme hybrid-light
"colorscheme hybrid
""colorscheme iangenzo
"colorscheme ibmedit
""colorscheme icansee
"colorscheme iceberg
""colorscheme impactG
"colorscheme impactjs
""colorscheme impact
"colorscheme industrial
""colorscheme industry
"colorscheme ingretu
""colorscheme inkpot
"colorscheme ir_black
""colorscheme ironman
"colorscheme jammy
""colorscheme jelleybeans
"colorscheme jellybeans
""colorscheme jellyx
"colorscheme jhdark
""colorscheme jhlight
"colorscheme jiks
""colorscheme kalisi
"colorscheme kaltex
""colorscheme kalt
"colorscheme kate
""colorscheme kellys
"colorscheme khaki
""colorscheme kib_darktango
"colorscheme kib_plastic
""colorscheme kiss
"colorscheme kkruby
""colorscheme kolor
"colorscheme kruby
""colorscheme kyle
"colorscheme landscape
""colorscheme last256
"colorscheme lazarus
""colorscheme legiblelight
"colorscheme leglight2
""colorscheme leo
"colorscheme less
""colorscheme lettuce
"colorscheme leya
""colorscheme lightcolors
"colorscheme lilac
""colorscheme lilydjwg_dark
"colorscheme lilydjwg_green
""colorscheme lilypink
"colorscheme lingodirector
""colorscheme liquidcarbon
"colorscheme list.txt
""colorscheme literal_tango
"colorscheme lizard256
""colorscheme lizard
"colorscheme lodestone
""colorscheme louver
"colorscheme lucius
""colorscheme luinnar
"colorscheme luna
""colorscheme lxvc
"colorscheme mac_classic
""colorscheme made_of_code
"colorscheme mango
""colorscheme manuscript
"colorscheme manxome
""colorscheme marklar
"colorscheme maroloccio
""colorscheme mars
"colorscheme martin_krischik
""colorscheme matrix
"colorscheme mayansmoke
""colorscheme mdark
"colorscheme mellow
""colorscheme metacosm
"colorscheme midnight2
""colorscheme midnight
"colorscheme miko
""colorscheme mint
"colorscheme mizore
""colorscheme mod_tcsoft
"colorscheme molokai
""colorscheme monokai-chris
"colorscheme monokain
""colorscheme Monokai
"colorscheme montz
""colorscheme mophiaDark
"colorscheme mophiaSmoke
""colorscheme mopkai
"colorscheme moria
""colorscheme moss
"colorscheme motus
""colorscheme MountainDew
"colorscheme mrkn256
""colorscheme mrpink
"colorscheme mud
""colorscheme muon
"colorscheme mustang
""colorscheme native
"colorscheme nature
""colorscheme navajo-night
"colorscheme navajo
""colorscheme nazca
"colorscheme nedit2
""colorscheme nedit
"colorscheme nefertiti
""colorscheme neon
"colorscheme nerv-ous
""colorscheme neutron
"colorscheme neverland2-darker
""colorscheme neverland2
"colorscheme neverland-darker
""colorscheme neverland
"colorscheme neverness
""colorscheme nevfn
"colorscheme newspaper
""colorscheme newsprint
"colorscheme nicotine
""colorscheme nightflight2
"colorscheme nightflight
""colorscheme nightshimmer
"colorscheme nightsky
""colorscheme night
"colorscheme night_vision
""colorscheme nightVision
"colorscheme nightwish
""colorscheme no_quarter
"colorscheme northland
""colorscheme northsky
"colorscheme norwaytoday
""colorscheme nour
"colorscheme nuvola
""colorscheme obsidian2
"colorscheme obsidian
""colorscheme oceanblack256
"colorscheme oceanblack
""colorscheme oceandeep
"colorscheme oceanlight
""colorscheme olive
"colorscheme orange
"colorscheme osx_like
""colorscheme otaku
"colorscheme pacific
""colorscheme paintbox
"colorscheme PapayaWhip
""colorscheme PaperColor
"colorscheme peaksea
""colorscheme pencil
"colorscheme peppers
""colorscheme perfect
"colorscheme pf_earth
""colorscheme phd
"colorscheme phphaxor
""colorscheme phpx
"colorscheme pic
""colorscheme pink
"colorscheme playroom
""colorscheme pleasant
"colorscheme potts
""colorscheme primary
"colorscheme print_bw
""colorscheme prmths
"colorscheme professional
""colorscheme proton
"colorscheme pspad
""colorscheme psql
"colorscheme putty
""colorscheme pw
"colorscheme pyte
""colorscheme python
"colorscheme quagmire
""colorscheme radicalgoodspeed
"colorscheme railscasts
""colorscheme rainbow_fine_blue
"colorscheme rainbow_fruit
""colorscheme rainbow_neon
"colorscheme random
""colorscheme rastafari
"colorscheme rcg_gui
""colorscheme rcg_term
"colorscheme rdark-terminal
""colorscheme rdark
"colorscheme redblack
""colorscheme redstring
"colorscheme refactor
""colorscheme relaxedgreen
"colorscheme reliable
""colorscheme reloaded
"colorscheme revolutions
""colorscheme robinhood
"colorscheme rootwater
""colorscheme rtl
"colorscheme sand
""colorscheme satori
"colorscheme saturn
""colorscheme scala
"colorscheme scite
""colorscheme sean
"colorscheme seashell
""colorscheme sea
"colorscheme selenitic
""colorscheme seoul256-light
"colorscheme seoul256
""colorscheme seoul
"colorscheme seti
""colorscheme settlemyer
"colorscheme sexy-railscasts
""colorscheme sf
"colorscheme shadesofamber
""colorscheme shobogenzo
"colorscheme sienna
""colorscheme sift
"colorscheme silent
""colorscheme simple256
"colorscheme simpleandfriendly
""colorscheme simple_b
"colorscheme simplewhite
"colorscheme skittles_berry
"colorscheme skittles_dark
colorscheme SlateDark
"colorscheme smp
""colorscheme smyck
"colorscheme softbluev2
""colorscheme softblue
"colorscheme softlight
"colorscheme solarized
"colorscheme sol-term
""colorscheme sol
"colorscheme sonofobsidian
""colorscheme sonoma
"colorscheme sorcerer
""colorscheme soso
"colorscheme southernlights
""colorscheme southwest-fog
"colorscheme spectro
""colorscheme spiderhawk
"colorscheme spring
""colorscheme stackoverflow
"colorscheme stingray
""colorscheme strange
"colorscheme strawimodo
""colorscheme summerfruit256
"colorscheme summerfruit
""colorscheme surveyor
"colorscheme swamplight
""colorscheme symfony
"colorscheme synic
"colorscheme tabula
"colorscheme tango2
""colorscheme tango-desert
"colorscheme tango-morning
""colorscheme tangoshady
"colorscheme tango
""colorscheme tangoX
"colorscheme taqua
""colorscheme tchaba2
"colorscheme tchaba
""colorscheme tcsoft
"colorscheme telstar
""colorscheme tesla
"colorscheme tetragrammaton
""colorscheme textmate16
"colorscheme thegoodluck
""colorscheme thestars
"colorscheme thor
"colorscheme tibet
"colorscheme tidy
"colorscheme tir_black
"colorscheme tolerable
""colorscheme tomatosoup
"colorscheme Tomorrow-Night-Blue
""colorscheme Tomorrow-Night-Bright
"colorscheme Tomorrow-Night-Eighties
"colorscheme Tomorrow-Night
"colorscheme Tomorrow
"colorscheme tony_light
"colorscheme toothpik
"colorscheme torte
"colorscheme transparent
"colorscheme trivial256
"colorscheme trogdor
""colorscheme turbo
"colorscheme tutticolori
""colorscheme twilight256
"colorscheme twilight
""colorscheme twitchy
"colorscheme two2tango
""colorscheme ubloh
"colorscheme umber-green
""colorscheme understated
"colorscheme underwater-mod
""colorscheme underwater
"colorscheme up
""colorscheme vanzan_color
"colorscheme vcbc
""colorscheme vc
"colorscheme vexorian
""colorscheme vibrantink
"colorscheme vilight
""colorscheme visualstudio
"colorscheme vividchalk
""colorscheme vj
"colorscheme void
""colorscheme vydark
"colorscheme vylight
""colorscheme wargrey
"colorscheme warm_grey
""colorscheme watermark
"colorscheme whitebox
""colorscheme whitedust
"colorscheme widower
""colorscheme win9xblueback
"colorscheme wintersday
""colorscheme winter
"colorscheme wombat256i
""colorscheme wombat256mod
"colorscheme wombat256
""colorscheme wombat
"colorscheme wood
""colorscheme wuye
"colorscheme xemacs
""colorscheme xian
"colorscheme xmaslights
""colorscheme xoria256
"colorscheme xterm16
""colorscheme yaml
"colorscheme yeller
""colorscheme zazen
"colorscheme zenburn
""colorscheme zenesque
"colorscheme zen
""colorscheme zephyr
"colorscheme zmrok
